import {
  User, Users, UserPlus, UserCheck, UserCircle, UserCog, UserMinus,
  Home, Building, Globe, Settings, Cog, Sliders, Wrench, 
  Bell, Inbox, Mail, MessageSquare, MessageCircle, Send, Reply,
  Calendar, Clock, Timer, AlarmClock,  History,
  File, FileText, FilePlus, FileMinus, Folder, FolderPlus, FolderOpen,
  List, ListOrdered, ListChecks, Check, CheckSquare, X, XCircle,
  Plus, Minus, Trash, Edit, Pencil, Save, Download, Upload,
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  Search, Filter, SortAsc, SortDesc, Eye, EyeOff, Lock, Unlock, Key,
  Link, ExternalLink, Share2, Bookmark, Star, Heart, ThumbsUp, ThumbsDown,
  AlertCircle, AlertTriangle, HelpCircle, Info, Lightbulb, Flag, Activity, Zap,
  BarChart, PieChart, LineChart, TrendingUp, TrendingDown,
  Image, Video, Camera, Play, Pause,  Mic, Volume, VolumeX,
  Tag, Tags, DollarSign, CreditCard, Wallet, Receipt,
  Phone, PhoneCall, Smartphone, Tablet, Laptop, Monitor,
  MapPin, Map, Compass, Navigation, Route,
  LogIn, LogOut, Shield, ShieldCheck, Fingerprint, QrCode,
  Clipboard, ClipboardCheck, ClipboardList,
  Package, Truck, ShoppingCart, Store, Gift,
  Sun, Moon, Cloud, CloudSun, CloudRain, CloudSnow, Wind,
  Rocket, Plane,
  Terminal, Code, Database, Server, Bug, GitBranch, GitCommit,
  ChevronFirst, ChevronLast, Move,  
} from 'lucide-react';

export const PreloadedIcons = {
  User, Users, UserPlus, UserCheck, UserCircle, UserCog, UserMinus,
  Home, Building, Globe, Settings, Cog, Sliders, Wrench, 
  Bell, Inbox, Mail, MessageSquare, MessageCircle, Send, Reply,
  Calendar, Clock, Timer, AlarmClock,  History,
  File, FileText, FilePlus, FileMinus, Folder, FolderPlus, FolderOpen,
  List, ListOrdered, ListChecks, Check, CheckSquare, X, XCircle,
  Plus, Minus, Trash, Edit, Pencil, Save, Download, Upload,
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  Search, Filter, SortAsc, SortDesc, Eye, EyeOff, Lock, Unlock, Key,
  Link, ExternalLink, Share2, Bookmark, Star, Heart, ThumbsUp, ThumbsDown,
  AlertCircle, AlertTriangle, HelpCircle, Info, Lightbulb, Flag, Activity, Zap,
  BarChart, PieChart, LineChart, TrendingUp, TrendingDown,
  Image, Video, Camera, Play, Pause,  Mic, Volume, VolumeX,
  Tag, Tags, DollarSign, CreditCard, Wallet, Receipt,
  Phone, PhoneCall, Smartphone, Tablet, Laptop, Monitor,
  MapPin, Map, Compass, Navigation, Route,
  LogIn, LogOut, Shield, ShieldCheck, Fingerprint, QrCode,
  Clipboard, ClipboardCheck, ClipboardList,
  Package, Truck, ShoppingCart, Store, Gift,
  Sun, Moon, Cloud, CloudSun, CloudRain, CloudSnow, Wind,
  Rocket, Plane,
  Terminal, Code, Database, Server, Bug, GitBranch, GitCommit,
  ChevronFirst, ChevronLast, Move
}